### PR TITLE
HandTrackingTool_OpenCV

### PR DESCRIPTION
**Pull request by Shivaminc**

### CODE REVIEW

**Comment by Shivaminc** [comment]
@thisisshub this project is showing "Excluded Project" on my Hactoberfest Profile can you explain me why is it showing that and how to resolve this issue.

**Comment by thisisshub** [comment]
@Shivaminc can you check the hacktoberfest webpage now and update me?

**Comment by Shivaminc** [comment]
@thisisshub it is still showing "Excluded Project".
Screenshot 2021-10-04 at 12 35 10 PM

**Comment by Shivaminc** [comment]
@thisisshub can you tell me the reason for this issue as it is showing the same on 2 more of my contribution.

**Comment by thisisshub** [comment]
Hacktoberfest has added quality standards that do not goes well with the programs uploaded to the repository. Read more [here](https://hacktoberfest.digitalocean.com/resources/qualitystandards)

**Comment by Shivaminc** [comment]
@thisisshub ok got it
thank you.

**Pull request merged**
